In [ ]:
# Assignment: Introduction to NumPy

# Part 1: NumPy Basics

# 1. Installing and Verifying NumPy
import numpy as np
print("NumPy is installed. Version:", np.__version__)

In [5]:
# 2. Creating Arrays
one_d_array = np.arange(1, 11)
two_d_array = np.random.randint(1, 101, (3, 3))
equally_spaced = np.linspace(0, 1, 10)
print("One-dimensional array:", one_d_array)
print("Two-dimensional array:\n", two_d_array)
print("Equally spaced array:", equally_spaced)


One-dimensional array: [ 1  2  3  4  5  6  7  8  9 10]
Two-dimensional array:
 [[91 57 34]
 [55 27 69]
 [35  4 63]]
Equally spaced array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [6]:
# 3. Array Properties
print("Shape of one_d_array:", one_d_array.shape)
print("Size of one_d_array:", one_d_array.size)
print("Data type of one_d_array:", one_d_array.dtype)

print("Shape of two_d_array:", two_d_array.shape)
print("Size of two_d_array:", two_d_array.size)
print("Data type of two_d_array:", two_d_array.dtype)

print("Shape of equally_spaced:", equally_spaced.shape)
print("Size of equally_spaced:", equally_spaced.size)
print("Data type of equally_spaced:", equally_spaced.dtype)

Shape of one_d_array: (10,)
Size of one_d_array: 10
Data type of one_d_array: int64
Shape of two_d_array: (3, 3)
Size of two_d_array: 9
Data type of two_d_array: int32
Shape of equally_spaced: (10,)
Size of equally_spaced: 10
Data type of equally_spaced: float64


In [8]:
# Part 2: Indexing & Slicing

# 4. Accessing Elements
fifth_element = one_d_array[4]
second_row = two_d_array[1]
first_three = one_d_array[:3]
one_d_array[-1] = 99

print("5th element of one_d_array:", fifth_element)
print("Second row of two_d_array:", second_row)
print("First three elements:", first_three)
print("Modified one_d_array:", one_d_array)


5th element of one_d_array: 5
Second row of two_d_array: [55 27 69]
First three elements: [1 2 3]
Modified one_d_array: [ 1  2  3  4  5  6  7  8  9 99]


In [9]:
# 5. Boolean Indexing & Fancy Indexing
greater_than_five = one_d_array[one_d_array > 5]
specific_rows = two_d_array[[0, 2]]

print("Elements greater than 5:", greater_than_five)
print("1st and 3rd rows of two_d_array:\n", specific_rows)

Elements greater than 5: [ 6  7  8  9 99]
1st and 3rd rows of two_d_array:
 [[91 57 34]
 [35  4 63]]


In [10]:
# Part 3: NumPy Operations

# 6. Mathematical Operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print("Addition:", array1 + array2)
print("Subtraction:", array1 - array2)
print("Multiplication:", array1 * array2)
print("Division:", array1 / array2)

print("Square root:", np.sqrt(array1))
print("Exponential:", np.exp(array1))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]


In [11]:
# 7. Aggregation Functions
sample_array = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(sample_array))
print("Mean:", np.mean(sample_array))
print("Standard Deviation:", np.std(sample_array))
print("Min:", np.min(sample_array))
print("Max:", np.max(sample_array))
print("Index of Min:", np.argmin(sample_array))
print("Index of Max:", np.argmax(sample_array))


Sum: 150
Mean: 30.0
Standard Deviation: 14.142135623730951
Min: 10
Max: 50
Index of Min: 0
Index of Max: 4


In [13]:
# 8. Matrix Operations
matrix1 = np.random.randint(1, 10, (3, 3))
matrix2 = np.random.randint(1, 10, (3, 3))

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Multiplication:\n", np.dot(matrix1, matrix2))

print("Transpose of Matrix 1:\n", matrix1.T)

try:
    inverse_matrix1 = np.linalg.inv(matrix1)
    print("Inverse of Matrix 1:\n", inverse_matrix1)
except np.linalg.LinAlgError:
    print("Matrix 1 is not invertible.")


Matrix 1:
 [[9 5 9]
 [7 5 2]
 [8 9 5]]
Matrix 2:
 [[8 5 5]
 [2 5 3]
 [1 4 9]]
Matrix Multiplication:
 [[ 91 106 141]
 [ 68  68  68]
 [ 87 105 112]]
Transpose of Matrix 1:
 [[9 7 8]
 [5 5 9]
 [9 2 5]]
Inverse of Matrix 1:
 [[ 0.04        0.32       -0.2       ]
 [-0.10857143 -0.15428571  0.25714286]
 [ 0.13142857 -0.23428571  0.05714286]]


In [14]:
# Part 4: Advanced NumPy

# 9. Reshaping & Concatenation
array_9 = np.arange(9)
reshaped_array = array_9.reshape((3, 3))

array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6], [7, 8]])

concat_rows = np.concatenate((array_a, array_b), axis=0)
concat_cols = np.concatenate((array_a, array_b), axis=1)

print("Reshaped 3x3 array:\n", reshaped_array)
print("Concatenated along rows:\n", concat_rows)
print("Concatenated along columns:\n", concat_cols)


Reshaped 3x3 array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]


In [15]:
# 10. Generating Special Arrays
identity_matrix = np.eye(4)
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 2))

print("Identity Matrix:\n", identity_matrix)
print("Array of Zeros:\n", zeros_array)
print("Array of Ones:\n", ones_array)


Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
